#ifndef _GLYPHS_H_
#define _GLYPHS_H_

#define GLYPH_SCREEN_DEPTH_UP 128
#define GLYPH_SCREEN_DEPTH_DOWN 129
#define GLYPH_WINDOW_CLOSE 130
#define GLYPH_WINDOW_DEPTH_UP 131
#define GLYPH_WINDOW_DEPTH_DOWN 132
#define GLYPH_RADIO_BUTTON_OFF 133
#define GLYPH_RADIO_BUTTON_ON 134
#define GLYPH_RADIO_BUTTON_MU 135
#define GLYPH_CHECK_BOX_OFF 136
#define GLYPH_CHECK_BOX_ON 137
#define GLYPH_CHECK_BOX_MU 138
#define GLYPH_SCREEN_FLIP_UP 139
#define GLYPH_SCREEN_FLIP_DOWN 140

#endif
