#ifndef _GLYPHS_H_
#define _GLYPHS_H_

/**
 * The Glyphs enum lists the mapping of ASCII codes to GUI icon images
 * such as the checkbox tick and shift key's arrow.
 */
enum Glyphs {
	GLYPH_SCREEN_DEPTH_UP = 128,
	GLYPH_SCREEN_DEPTH_DOWN = 129,
	GLYPH_WINDOW_CLOSE = 130,
	GLYPH_WINDOW_DEPTH_UP = 131,
	GLYPH_WINDOW_DEPTH_DOWN = 132,
	GLYPH_RADIO_BUTTON_OFF = 133,
	GLYPH_RADIO_BUTTON_ON = 134,
	GLYPH_RADIO_BUTTON_MU = 135,
	GLYPH_CHECK_BOX_OFF = 136,
	GLYPH_CHECK_BOX_ON = 137,
	GLYPH_CHECK_BOX_MU = 138,
	GLYPH_SCREEN_FLIP_UP = 139,
	GLYPH_SCREEN_FLIP_DOWN = 140,
	GLYPH_ARROW_UP = 141,
	GLYPH_ARROW_DOWN = 142,
	GLYPH_ARROW_LEFT = 143,
	GLYPH_ARROW_RIGHT = 144,
	GLYPH_CYCLE = 145,
	GLYPH_BACKSPACE = 146,
	GLYPH_RETURN = 147,
	GLYPH_SHIFT = 148
};

#endif
