bmp2font /fonttype packedfont1 /infile arial9.bmp /classname Arial9
bmp2font /fonttype packedfont1 /infile bankgothic12.bmp /classname BankGothic12
bmp2font /fonttype packedfont1 /infile batang12.bmp /classname Batang12
bmp2font /fonttype packedfont1 /infile batang14.bmp /classname Batang14
bmp2font /fonttype packedfont1 /infile batang15.bmp /classname Batang15
bmp2font /fonttype packedfont1 /infile courier12.bmp /classname Courier12
bmp2font /fonttype packedfont1 /infile courier12b.bmp /classname Courier12b
bmp2font /fonttype packedfont1 /infile courier.bmp /classname Courier
bmp2font /fonttype packedfont1 /infile couriernew10.bmp /classname CourierNew10
bmp2font /fonttype packedfont1 /infile couriernew12.bmp /classname CourierNew12
bmp2font /fonttype packedfont1 /infile dotum13.bmp /classname Dotum13
bmp2font /fonttype packedfont1 /infile FixedSys12.bmp /classname FixedSys12
bmp2font /fonttype packedfont1 /infile Garamond10.bmp /classname Garamond10
bmp2font /fonttype packedfont1 /infile GillSans11.bmp /classname GillSans11
bmp2font /fonttype packedfont1 /infile GillSans11b.bmp /classname GillSans11b
bmp2font /fonttype packedfont1 /infile Gloucester10.bmp /classname Gloucester10
bmp2font /fonttype packedfont1 /infile Goudy9.bmp /classname Goudy9
bmp2font /fonttype packedfont1 /infile Gulimche12.bmp /classname Gulimche12
bmp2font /fonttype packedfont1 /infile Gulimche12b.bmp /classname Gulimche12b
bmp2font /fonttype packedfont1 /infile Gungsuh12.bmp /classname Gungsuh12
bmp2font /fonttype packedfont1 /infile Gungsuh15.bmp /classname Gungsuh15
bmp2font /fonttype packedfont1 /infile Gungsuhche11.bmp /classname Gungsuhche11
bmp2font /fonttype packedfont1 /infile Gungsuhche15.bmp /classname Gungsuhche15
bmp2font /fonttype packedfont1 /infile Kartika9.bmp /classname Kartika9
bmp2font /fonttype packedfont1 /infile Kartika10.bmp /classname Kartika10
bmp2font /fonttype packedfont1 /infile Latha9.bmp /classname Latha9
bmp2font /fonttype packedfont1 /infile Latha10.bmp /classname Latha10
bmp2font /fonttype packedfont1 /infile Latha15.bmp /classname Latha15
bmp2font /fonttype packedfont1 /infile LucidaCalligraphy14.bmp /classname LucidaCalligraphy14
bmp2font /fonttype packedfont1 /infile Mangal9.bmp /classname Mangal9
bmp2font /fonttype packedfont1 /infile Modern9.bmp /classname Modern9
bmp2font /fonttype packedfont1 /infile Modern9b.bmp /classname Modern9b
bmp2font /fonttype packedfont1 /infile MSGothic8.bmp /classname MSGothic8
bmp2font /fonttype packedfont1 /infile MSGothic9.bmp /classname MSGothic9
bmp2font /fonttype packedfont1 /infile MSSans9.bmp /classname MSSans9
bmp2font /fonttype packedfont1 /infile MSSans9b.bmp /classname MSSans9b
bmp2font /fonttype packedfont1 /infile MSSerif11.bmp /classname MSSerif11
bmp2font /fonttype packedfont1 /infile MSSerif11b.bmp /classname MSSerif11b
bmp2font /fonttype packedfont1 /infile NewTopaz.bmp /classname NewTopaz
bmp2font /fonttype packedfont1 /infile OCRFont8.bmp /classname OCRFont8
bmp2font /fonttype packedfont1 /infile PoorRichard9.bmp /classname PoorRichard9
bmp2font /fonttype packedfont1 /infile PoorRichard12.bmp /classname PoorRichard12
bmp2font /fonttype packedfont1 /infile Roman9b.bmp /classname Roman9b
bmp2font /fonttype packedfont1 /infile Roman11i.bmp /classname Roman11i
bmp2font /fonttype packedfont1 /infile Roman13.bmp /classname Roman13
bmp2font /fonttype packedfont1 /infile Roman13i.bmp /classname Roman13i
bmp2font /fonttype packedfont1 /infile Script9b.bmp /classname Script9b
bmp2font /fonttype packedfont1 /infile TimesNewRoman9.bmp /classname TimesNewRoman9
bmp2font /fonttype packedfont1 /infile Topaz.bmp /classname Topaz
bmp2font /fonttype packedfont1 /infile Tunga8.bmp /classname Tunga8